---
- !ruby/struct:Query
  name: OmniFocus inbox size
  sql: SELECT count(*) FROM Task WHERE inInbox = 1;
  color: red
- !ruby/struct:Query
  name: OmniFocus Flagged Tasks
  sql: SELECT name FROM Task WHERE effectiveFlagged = 1 and dateCompleted is null;
  color: blue
